// Code generated by sdk/gen/gen_clients.py. DO NOT EDIT.
#nullable enable
using System.Text.Json;

namespace Dogabot.Sdk;

public partial class Client
{
    /// <summary>Every OpenAPI operationId mirrored by this SDK.</summary>
    public static readonly string[] OperationIds =
    [
        "getMe",
        "getMeStatistics",
        "getMePositions",
        "getMePositionlegs",
        "getMeOrders",
        "getMeSignals",
        "getMeEmitters",
        "postMeEmittersSummary",
        "postAutomationsSummary",
        "getFollowers",
        "postFollowers",
        "getFollowersById",
        "patchFollowersById",
        "deleteFollowersById",
        "postFollowersSummary",
        "getFollowersSummaryById",
        "getFollowersPnlseriesById",
        "getFollowersPositionById",
        "getBots",
        "postBots",
        "getBotsById",
        "patchBotsById",
        "deleteBotsById",
        "postBotsSummary",
        "getBotsPnlseriesById",
        "getBotsPositionById",
        "getEmitters",
        "postEmitters",
        "getEmittersById",
        "patchEmittersById",
        "deleteEmittersById",
        "postEmittersSummary",
        "getEmittersSummaryById",
        "getEmittersCurated",
        "getEmittersPnlseriesById",
        "getEmittersPositionById",
        "getPortfolios",
        "postPortfolios",
        "getPortfoliosById",
        "patchPortfoliosById",
        "deletePortfoliosById",
        "postPortfoliosSummary",
        "getPortfoliosPnlseriesById",
        "getPortfoliosPositionsById",
        "getOrders",
        "getSignals",
        "getBacktestQuota",
        "getBacktests",
        "getBacktestsSummary",
        "getBacktestByJob_id",
        "getBacktestSignalsByJob_id",
        "getBacktestBulkSeed",
        "getBacktestBulkBatches",
        "getBacktestBulkBatchesByBatch_id",
        "getTicker",
        "getFundingrate",
        "getMarketOrderbook",
        "getMarketTrades",
        "getMarkets",
        "getMarketsAssetprofile",
        "getExchanges",
        "getMarkettypes",
        "getMarketplaceSearch",
        "getMarketplaceSellersByHandle",
        "getDatafeedHistory",
        "postMarketsSymbolcorrelation",
        "postMarketsSymbolvolatility",
        "postMarketsSymbolfeebreakeven",
        "getTerminalOrders",
        "getTerminalOrdersByclientorderidByClient_order_id",
        "getTerminalPositions",
        "getTerminalSymbolrules",
        "getTerminalOrdercapabilities",
        "getExchangeBalances",
        "getExchangePositions",
        "getExchangeMarginsummary",
        "getExchangeOrders",
        "getExchangeTrades",
        "getExchangeIncome",
        "getExchangeOpenablenotional",
        "postExchangeLeverage",
        "postExchangeCancelorder",
        "postExchangeCancelorders",
        "getCredentials",
        "postCredentials",
        "getTags",
        "postTags",
        "getMeStatisticsBytag",
        "postFollowersStartById",
        "postFollowersStopById",
        "postBotsStartById",
        "postBotsStopById",
        "postBotsBooksById",
        "postFollowersBooksById",
        "postEmittersStartById",
        "postEmittersStopById",
        "postPortfoliosStartById",
        "postPortfoliosStopById",
        "putFollowersTagsById",
        "putBotsTagsById",
        "putEmittersTagsById",
        "putPortfoliosTagsById",
        "patchTagsById",
        "deleteTagsById",
        "putCredentialsById",
        "deleteCredentialsById",
        "postCredentialsDefaultById",
        "postBacktest",
        "postBacktestBulk",
        "postBacktestBulkBatchesRerunByBatch_id",
        "postBacktestBulkBatchesCancelByBatch_id",
        "postBacktestCancelByJob_id",
        "postTerminalPlaceorder",
        "postTerminalCancelorder",
        "getAiChatQuota",
        "getAiChatConversations",
        "postAiChatConversations",
        "getAiChatConversationsById",
        "postAiChatConversationsMessagesById",
        "postAiChatConversationsToolsConfirmByIdCall_id",
    ];

    /// <summary>Calls getMe.</summary>
    public Task<JsonElement> GetMeAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/me";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMeStatistics.</summary>
    public Task<JsonElement> GetMeStatisticsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/me/statistics";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMePositions.</summary>
    public Task<JsonElement> GetMePositionsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/me/positions";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMePositionlegs.</summary>
    public Task<JsonElement> GetMePositionlegsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/me/position-legs";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMeOrders.</summary>
    public Task<JsonElement> GetMeOrdersAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/me/orders";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMeSignals.</summary>
    public Task<JsonElement> GetMeSignalsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/me/signals";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMeEmitters.</summary>
    public Task<JsonElement> GetMeEmittersAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/me/emitters";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls postMeEmittersSummary.</summary>
    public Task<JsonElement> PostMeEmittersSummaryAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/me/emitters/summary";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls postAutomationsSummary.</summary>
    public Task<JsonElement> PostAutomationsSummaryAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/automations/summary";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getFollowers.</summary>
    public Task<JsonElement> GetFollowersAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/followers";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls postFollowers.</summary>
    public Task<JsonElement> PostFollowersAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/followers";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getFollowersById.</summary>
    public Task<JsonElement> GetFollowersByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/followers/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls patchFollowersById.</summary>
    public Task<JsonElement> PatchFollowersByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/followers/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Patch, path, options, body);
    }

    /// <summary>Calls deleteFollowersById.</summary>
    public Task<JsonElement> DeleteFollowersByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/followers/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Delete, path, options, body);
    }

    /// <summary>Calls postFollowersSummary.</summary>
    public Task<JsonElement> PostFollowersSummaryAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/followers/summary";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getFollowersSummaryById.</summary>
    public Task<JsonElement> GetFollowersSummaryByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/followers/summary/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getFollowersPnlseriesById.</summary>
    public Task<JsonElement> GetFollowersPnlseriesByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/followers/{id}/pnl-series";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getFollowersPositionById.</summary>
    public Task<JsonElement> GetFollowersPositionByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/followers/{id}/position";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getBots.</summary>
    public Task<JsonElement> GetBotsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/bots";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls postBots.</summary>
    public Task<JsonElement> PostBotsAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/bots";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getBotsById.</summary>
    public Task<JsonElement> GetBotsByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/bots/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls patchBotsById.</summary>
    public Task<JsonElement> PatchBotsByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/bots/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Patch, path, options, body);
    }

    /// <summary>Calls deleteBotsById.</summary>
    public Task<JsonElement> DeleteBotsByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/bots/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Delete, path, options, body);
    }

    /// <summary>Calls postBotsSummary.</summary>
    public Task<JsonElement> PostBotsSummaryAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/bots/summary";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getBotsPnlseriesById.</summary>
    public Task<JsonElement> GetBotsPnlseriesByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/bots/{id}/pnl-series";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getBotsPositionById.</summary>
    public Task<JsonElement> GetBotsPositionByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/bots/{id}/position";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getEmitters.</summary>
    public Task<JsonElement> GetEmittersAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/emitters";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls postEmitters.</summary>
    public Task<JsonElement> PostEmittersAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/emitters";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getEmittersById.</summary>
    public Task<JsonElement> GetEmittersByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/emitters/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls patchEmittersById.</summary>
    public Task<JsonElement> PatchEmittersByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/emitters/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Patch, path, options, body);
    }

    /// <summary>Calls deleteEmittersById.</summary>
    public Task<JsonElement> DeleteEmittersByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/emitters/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Delete, path, options, body);
    }

    /// <summary>Calls postEmittersSummary.</summary>
    public Task<JsonElement> PostEmittersSummaryAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/emitters/summary";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getEmittersSummaryById.</summary>
    public Task<JsonElement> GetEmittersSummaryByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/emitters/summary/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getEmittersCurated.</summary>
    public Task<JsonElement> GetEmittersCuratedAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/emitters/curated";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getEmittersPnlseriesById.</summary>
    public Task<JsonElement> GetEmittersPnlseriesByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/emitters/{id}/pnl-series";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getEmittersPositionById.</summary>
    public Task<JsonElement> GetEmittersPositionByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/emitters/{id}/position";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getPortfolios.</summary>
    public Task<JsonElement> GetPortfoliosAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/portfolios";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls postPortfolios.</summary>
    public Task<JsonElement> PostPortfoliosAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/portfolios";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getPortfoliosById.</summary>
    public Task<JsonElement> GetPortfoliosByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/portfolios/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls patchPortfoliosById.</summary>
    public Task<JsonElement> PatchPortfoliosByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/portfolios/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Patch, path, options, body);
    }

    /// <summary>Calls deletePortfoliosById.</summary>
    public Task<JsonElement> DeletePortfoliosByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/portfolios/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Delete, path, options, body);
    }

    /// <summary>Calls postPortfoliosSummary.</summary>
    public Task<JsonElement> PostPortfoliosSummaryAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/portfolios/summary";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getPortfoliosPnlseriesById.</summary>
    public Task<JsonElement> GetPortfoliosPnlseriesByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/portfolios/{id}/pnl-series";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getPortfoliosPositionsById.</summary>
    public Task<JsonElement> GetPortfoliosPositionsByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/portfolios/{id}/positions";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getOrders.</summary>
    public Task<JsonElement> GetOrdersAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/orders";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getSignals.</summary>
    public Task<JsonElement> GetSignalsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/signals";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getBacktestQuota.</summary>
    public Task<JsonElement> GetBacktestQuotaAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/backtest/quota";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getBacktests.</summary>
    public Task<JsonElement> GetBacktestsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/backtests";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getBacktestsSummary.</summary>
    public Task<JsonElement> GetBacktestsSummaryAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/backtests/summary";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getBacktestByJob_id.</summary>
    public Task<JsonElement> GetBacktestByJob_idAsync(object jobId, RequestOptions? options = null)
    {
        var path = "/api/v1/backtest/{job_id}";
        path = path.Replace("{job_id}", Uri.EscapeDataString(Convert.ToString(jobId) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getBacktestSignalsByJob_id.</summary>
    public Task<JsonElement> GetBacktestSignalsByJob_idAsync(object jobId, RequestOptions? options = null)
    {
        var path = "/api/v1/backtest/{job_id}/signals";
        path = path.Replace("{job_id}", Uri.EscapeDataString(Convert.ToString(jobId) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getBacktestBulkSeed.</summary>
    public Task<JsonElement> GetBacktestBulkSeedAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/backtest/bulk/seed";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getBacktestBulkBatches.</summary>
    public Task<JsonElement> GetBacktestBulkBatchesAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/backtest/bulk/batches";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getBacktestBulkBatchesByBatch_id.</summary>
    public Task<JsonElement> GetBacktestBulkBatchesByBatch_idAsync(object batch_id, RequestOptions? options = null)
    {
        var path = "/api/v1/backtest/bulk/batches/{batch_id}";
        path = path.Replace("{batch_id}", Uri.EscapeDataString(Convert.ToString(batch_id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getTicker.</summary>
    public Task<JsonElement> GetTickerAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/ticker";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getFundingrate.</summary>
    public Task<JsonElement> GetFundingrateAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/funding-rate";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMarketOrderbook.</summary>
    public Task<JsonElement> GetMarketOrderbookAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/market/orderbook";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMarketTrades.</summary>
    public Task<JsonElement> GetMarketTradesAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/market/trades";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMarkets.</summary>
    public Task<JsonElement> GetMarketsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/markets";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMarketsAssetprofile.</summary>
    public Task<JsonElement> GetMarketsAssetprofileAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/markets/asset-profile";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getExchanges.</summary>
    public Task<JsonElement> GetExchangesAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/exchanges";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMarkettypes.</summary>
    public Task<JsonElement> GetMarkettypesAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/market-types";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMarketplaceSearch.</summary>
    public Task<JsonElement> GetMarketplaceSearchAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/marketplace/search";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getMarketplaceSellersByHandle.</summary>
    public Task<JsonElement> GetMarketplaceSellersByHandleAsync(object handle, RequestOptions? options = null)
    {
        var path = "/api/v1/marketplace/sellers/{handle}";
        path = path.Replace("{handle}", Uri.EscapeDataString(Convert.ToString(handle) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getDatafeedHistory.</summary>
    public Task<JsonElement> GetDatafeedHistoryAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/datafeed/history";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls postMarketsSymbolcorrelation.</summary>
    public Task<JsonElement> PostMarketsSymbolcorrelationAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/markets/symbol-correlation";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls postMarketsSymbolvolatility.</summary>
    public Task<JsonElement> PostMarketsSymbolvolatilityAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/markets/symbol-volatility";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls postMarketsSymbolfeebreakeven.</summary>
    public Task<JsonElement> PostMarketsSymbolfeebreakevenAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/markets/symbol-fee-breakeven";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getTerminalOrders.</summary>
    public Task<JsonElement> GetTerminalOrdersAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/terminal/orders";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getTerminalOrdersByclientorderidByClient_order_id.</summary>
    public Task<JsonElement> GetTerminalOrdersByclientorderidByClient_order_idAsync(object clientOrderId, RequestOptions? options = null)
    {
        var path = "/api/v1/terminal/orders/by-client-order-id/{client_order_id}";
        path = path.Replace("{client_order_id}", Uri.EscapeDataString(Convert.ToString(clientOrderId) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getTerminalPositions.</summary>
    public Task<JsonElement> GetTerminalPositionsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/terminal/positions";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getTerminalSymbolrules.</summary>
    public Task<JsonElement> GetTerminalSymbolrulesAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/terminal/symbol-rules";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getTerminalOrdercapabilities.</summary>
    public Task<JsonElement> GetTerminalOrdercapabilitiesAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/terminal/order-capabilities";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getExchangeBalances.</summary>
    public Task<JsonElement> GetExchangeBalancesAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/exchange/balances";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getExchangePositions.</summary>
    public Task<JsonElement> GetExchangePositionsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/exchange/positions";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getExchangeMarginsummary.</summary>
    public Task<JsonElement> GetExchangeMarginsummaryAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/exchange/margin-summary";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getExchangeOrders.</summary>
    public Task<JsonElement> GetExchangeOrdersAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/exchange/orders";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getExchangeTrades.</summary>
    public Task<JsonElement> GetExchangeTradesAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/exchange/trades";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getExchangeIncome.</summary>
    public Task<JsonElement> GetExchangeIncomeAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/exchange/income";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getExchangeOpenablenotional.</summary>
    public Task<JsonElement> GetExchangeOpenablenotionalAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/exchange/openable-notional";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls postExchangeLeverage.</summary>
    public Task<JsonElement> PostExchangeLeverageAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/exchange/leverage";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls postExchangeCancelorder.</summary>
    public Task<JsonElement> PostExchangeCancelorderAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/exchange/cancel-order";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls postExchangeCancelorders.</summary>
    public Task<JsonElement> PostExchangeCancelordersAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/exchange/cancel-orders";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getCredentials.</summary>
    public Task<JsonElement> GetCredentialsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/credentials";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls postCredentials.</summary>
    public Task<JsonElement> PostCredentialsAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/credentials";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getTags.</summary>
    public Task<JsonElement> GetTagsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/tags";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls postTags.</summary>
    public Task<JsonElement> PostTagsAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/tags";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getMeStatisticsBytag.</summary>
    public Task<JsonElement> GetMeStatisticsBytagAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/me/statistics/by-tag";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls postFollowersStartById.</summary>
    public Task<JsonElement> PostFollowersStartByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/followers/{id}/start";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options);
    }

    /// <summary>Calls postFollowersStopById.</summary>
    public Task<JsonElement> PostFollowersStopByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/followers/{id}/stop";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options);
    }

    /// <summary>Calls postBotsStartById.</summary>
    public Task<JsonElement> PostBotsStartByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/bots/{id}/start";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options);
    }

    /// <summary>Calls postBotsStopById.</summary>
    public Task<JsonElement> PostBotsStopByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/bots/{id}/stop";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options);
    }

    /// <summary>Calls postBotsBooksById.</summary>
    public Task<JsonElement> PostBotsBooksByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/bots/{id}/books";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls postFollowersBooksById.</summary>
    public Task<JsonElement> PostFollowersBooksByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/followers/{id}/books";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls postEmittersStartById.</summary>
    public Task<JsonElement> PostEmittersStartByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/emitters/{id}/start";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options);
    }

    /// <summary>Calls postEmittersStopById.</summary>
    public Task<JsonElement> PostEmittersStopByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/emitters/{id}/stop";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options);
    }

    /// <summary>Calls postPortfoliosStartById.</summary>
    public Task<JsonElement> PostPortfoliosStartByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/portfolios/{id}/start";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options);
    }

    /// <summary>Calls postPortfoliosStopById.</summary>
    public Task<JsonElement> PostPortfoliosStopByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/portfolios/{id}/stop";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options);
    }

    /// <summary>Calls putFollowersTagsById.</summary>
    public Task<JsonElement> PutFollowersTagsByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/followers/{id}/tags";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Put, path, options, body);
    }

    /// <summary>Calls putBotsTagsById.</summary>
    public Task<JsonElement> PutBotsTagsByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/bots/{id}/tags";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Put, path, options, body);
    }

    /// <summary>Calls putEmittersTagsById.</summary>
    public Task<JsonElement> PutEmittersTagsByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/emitters/{id}/tags";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Put, path, options, body);
    }

    /// <summary>Calls putPortfoliosTagsById.</summary>
    public Task<JsonElement> PutPortfoliosTagsByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/portfolios/{id}/tags";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Put, path, options, body);
    }

    /// <summary>Calls patchTagsById.</summary>
    public Task<JsonElement> PatchTagsByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/tags/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Patch, path, options, body);
    }

    /// <summary>Calls deleteTagsById.</summary>
    public Task<JsonElement> DeleteTagsByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/tags/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Delete, path, options, body);
    }

    /// <summary>Calls putCredentialsById.</summary>
    public Task<JsonElement> PutCredentialsByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/credentials/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Put, path, options, body);
    }

    /// <summary>Calls deleteCredentialsById.</summary>
    public Task<JsonElement> DeleteCredentialsByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/credentials/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Delete, path, options, body);
    }

    /// <summary>Calls postCredentialsDefaultById.</summary>
    public Task<JsonElement> PostCredentialsDefaultByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/credentials/{id}/default";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options);
    }

    /// <summary>Calls postBacktest.</summary>
    public Task<JsonElement> PostBacktestAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/backtest";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls postBacktestBulk.</summary>
    public Task<JsonElement> PostBacktestBulkAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/backtest/bulk";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls postBacktestBulkBatchesRerunByBatch_id.</summary>
    public Task<JsonElement> PostBacktestBulkBatchesRerunByBatch_idAsync(object batch_id, RequestOptions? options = null)
    {
        var path = "/api/v1/backtest/bulk/batches/{batch_id}/rerun";
        path = path.Replace("{batch_id}", Uri.EscapeDataString(Convert.ToString(batch_id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options);
    }

    /// <summary>Calls postBacktestBulkBatchesCancelByBatch_id.</summary>
    public Task<JsonElement> PostBacktestBulkBatchesCancelByBatch_idAsync(object batch_id, RequestOptions? options = null)
    {
        var path = "/api/v1/backtest/bulk/batches/{batch_id}/cancel";
        path = path.Replace("{batch_id}", Uri.EscapeDataString(Convert.ToString(batch_id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options);
    }

    /// <summary>Calls postBacktestCancelByJob_id.</summary>
    public Task<JsonElement> PostBacktestCancelByJob_idAsync(object jobId, RequestOptions? options = null)
    {
        var path = "/api/v1/backtest/{job_id}/cancel";
        path = path.Replace("{job_id}", Uri.EscapeDataString(Convert.ToString(jobId) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options);
    }

    /// <summary>Calls postTerminalPlaceorder.</summary>
    public Task<JsonElement> PostTerminalPlaceorderAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/terminal/place-order";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls postTerminalCancelorder.</summary>
    public Task<JsonElement> PostTerminalCancelorderAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/terminal/cancel-order";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getAiChatQuota.</summary>
    public Task<JsonElement> GetAiChatQuotaAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/ai/chat/quota";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls getAiChatConversations.</summary>
    public Task<JsonElement> GetAiChatConversationsAsync(RequestOptions? options = null)
    {
        var path = "/api/v1/ai/chat/conversations";
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls postAiChatConversations.</summary>
    public Task<JsonElement> PostAiChatConversationsAsync(object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/ai/chat/conversations";
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls getAiChatConversationsById.</summary>
    public Task<JsonElement> GetAiChatConversationsByIdAsync(object id, RequestOptions? options = null)
    {
        var path = "/api/v1/ai/chat/conversations/{id}";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        return RequestAsync(HttpMethod.Get, path, options);
    }

    /// <summary>Calls postAiChatConversationsMessagesById.</summary>
    public Task<JsonElement> PostAiChatConversationsMessagesByIdAsync(object id, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/ai/chat/conversations/{id}/messages";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

    /// <summary>Calls postAiChatConversationsToolsConfirmByIdCall_id.</summary>
    public Task<JsonElement> PostAiChatConversationsToolsConfirmByIdCall_idAsync(object id, object callId, object? body = null, RequestOptions? options = null)
    {
        var path = "/api/v1/ai/chat/conversations/{id}/tools/{call_id}/confirm";
        path = path.Replace("{id}", Uri.EscapeDataString(Convert.ToString(id) ?? ""), StringComparison.Ordinal);
        path = path.Replace("{call_id}", Uri.EscapeDataString(Convert.ToString(callId) ?? ""), StringComparison.Ordinal);
        options ??= new RequestOptions();
        options.Write = true;
        return RequestAsync(HttpMethod.Post, path, options, body);
    }

}
